### ISSUE TITLE
Can't install via composer!

### ISSUE THREAD

**Issue by OliveIT** [peercoin/peercoin-php-rpc#1]
Where is this package on packagist?

**Comment by abraovic** [comment]
Hi @OliveIT 

It is not available on packagist. Someone from Peercoin foundation should made it available since I do not have permissions to do that. I'll contact someone to make this available on packagist. Hope they'll do that soon.

Ante

**Comment by abraovic** [comment]
Hi @OliveIT 

It's available on packagist now.

```
composer require abraovic/peercoin-php-rpc
```

**Comment by lezabour** [comment]
Hi
still have error:
 

 

> Could not find a version of package abraovic/peercoin-php-rpc matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

Maybe you need to create a release on github ?

**Comment by abraovic** [comment]
Hi @lezabour,

Can you try it now. Now there is v1.0 tag. According to [this article](https://jameshfisher.com/2017/11/06/how-to-release-a-composer-package/) it should work.

<img width="509" alt="Screenshot 2019-05-22 at 20 25 07" src="https://user-images.githubusercontent.com/5057523/58199031-ebf09d80-7ccf-11e9-8a10-d349fa178770.png">

**Comment by lezabour** [comment]
yes it's good now!

thanks
