### ISSUE TITLE
The RpcClient class attribute, "requests", is not flushed after the call to execute()

### ISSUE THREAD

**Issue by tandem5** [peercoin/peercoin-php-rpc#4]
Requests will accumulate between sequential calls from the same RPCClient instantiation. Moreover an illegal string offset warning will occur if a single request (non-batch) is made first. The warning is derived from the first, single request being classified as non-batch and thus the elements of the encapsulated array are elevated to the parent array of "requests." When the second request is made, because "requests" is still populated, it is interpreted as batch. The batch method will then tokenize mixed elements including strings and interpret them as arrays.

I suggest flushing the "requests" attribute after the "options" array is defined in the "request" method.

**Comment by abraovic** [comment]
Thanks for that suggestion @tandem5. I have pushed a new commit as suggested.
